### ISSUE TITLE
Shotcut crashes on Loading mlt file (Windows 10) 

### ISSUE THREAD

**Issue by Aiphares** [mltframework/shotcut#712]
Hello there, 

i was just working on a Video when i accidentally dropped an audio file in the video timeline, which caused Shotcut to crash.  Ever since, when i try loading this MLT file shotcut directly crashes. 

I still remember though that similar to #531 i think i had the project file itself in the list, so it might be a self reference problem. 

i am running the current version 19.02.28

is there any way to open the File again? 

[bdomage.zip](https://github.com/mltframework/shotcut/files/2973622/bdomage.zip)

**Comment by Butterfly** [comment]
Hi.. "Just" a normal user here. I came in here to *nervously* ask if there's an XML type file that you can manually edit.

THEN I read the following [#531 comment](https://github.com/mltframework/shotcut/issues/531#issuecomment-379494836):

> You are affected by this MLT bug. Your project includes itself (MLT XML) in the Playlist. You may have done this by using File > Open MLT XML as Clip and then choosing the project you are editing. I need to prevent this, but it should be fairly obvious that this will cause a problem.
I edited your XML to remove that self-reference, and I uploaded it to here. Let me know when you have downloaded it; so I can remove it.

1) COOL. There **are** manually editable files (with tons of references to XML if you `grep` Shotcut's git clone for the same, by the way).

2) **Don't forget to backup** with at least one safely saved copy before playing with these files. :smile: 

So what I was thinking is: Can you grab Issue #531's original poster's uploaded file and the Dev's revised copy to compare what the Dev changed that worked and helped close that issue for them? That will confirm one way or another if your issue is similar to #531 .

If your project still crashes after that, especially if that wasn't your problem at all, maybe you could next nose around to see what file contains a reference to the audio file that was touched just before the original crash.

If this was me experiencing this, I would again `grep` or otherwise comparably search the *project's own home directory* to locate which file contains the name of the potentially offending audio file.

If a reference is found in a manually editable file, you could play around with deleting (perhaps just "commenting out"?) that reference then keep attempting to reload the project along the way.

Even if both options still don't help, attempting them won't be a waste of time and effort. It's a great way to learn more about how these things work overall. You get to see how one single change in those files affects the project's outcome. It can be a fun and very techie-empowering ah-*ha* moment if it actually works. :smile:

**Comment by Aiphares** [comment]
hey Butterfly!

Yes i have been nosing around in my file to search for the Audio file but funny enough only the video files seem to be mentioned, even though they seem to get mentioned several times (maybe ones in the timeline and ones in the library). 

Didnt find either audio files ( i had 2, named bdo01 and bdo2) even though i know that the first was working.  

one of my guesses was that maybe bdo2 got added into the video line since i dropped it wrongly but then it would show up in the file which it doesnt.

i wanted to check the 2 files but can't find the second file anymore. As mentioned in the thread i guess it got deleted :/

**Comment by ddennedy** [comment]
Yes, you included the project in itself. I already added code to not allow that, but you found a loophole. I need to know how you did it in order to make a code fix. Meanwhile, I fixed your project. 
[bdomage.mlt.txt](https://github.com/mltframework/shotcut/files/2974765/bdomage.mlt.txt)

**Comment by ddennedy** [comment]
I just tried several ways of adding to the playlist, and I could not figure out a way to bypass the check.

**Comment by ddennedy** [comment]
P.S. All I did to find this problem is open the .mlt file in a text editor and search for "bdoimage.mlt". I found something `<producer id="playlist0">`. Then, I found that referenced in an `<entry>` within `<playlist id="main bin">`. To fix it, I removed the `<producer id="playlist0">` that is referring to itself. Then, I removed the now invalid playlist `<entry>`.

**Comment by Aiphares** [comment]
Hey Dan! 
Thanks for the changes and the explanation, i could see what you did there. Sadly i still cant load your fixed version without a crash :/ 

this was my first project so what i did was pulling the Project itself into the list and then the timeaxis in the bottom since i thought thats how you are supposed to start.

maybe i have a defective install and i will try to reinstall the program. 

meanwhile i have recorded a video of how i do it, since i was able to exactly replicate this crash several times.  maybe if you see how i did it you will be able to replicate it as well 

https://youtu.be/XC6CEufYflA

**Comment by Aiphares** [comment]
hey again,

i just tried doing a full reinstall but somehow it keeps showing up without a reset.

so after uninstalling,  deleting the appdata/Local/ folder AND the local/temp folder  and THEN installing a newly downloaded version from github  upon startup it still shows me my project folder as well as my recently opened files and projects as if nothing happened. weird

**Comment by ddennedy** [comment]
There was more the 1 instance of bdoimage.mlt appearing within itself. The second one was left for you as an exercise. ;-) Just kidding. I overlooked it. Here it is again.

[bdomage-fixed-2.mlt.txt](https://github.com/mltframework/shotcut/files/2975681/bdomage-fixed-2.mlt.txt)

I found the loophole in your screencast video - dragging from Recent to Playlist. Sometimes, I forget that you can drag from recent. I am not sure why you are doing something that is known to cause a big problem, but it will be nice to fix this.

> i just tried doing a full reinstall but somehow it keeps showing up without a reset.

On Windows, there is a a registry, and you have to use App Data Directory > Set... to make it use an INI file for settings instead of the registry. See [FAQ](https://shotcut.org/FAQ/#where-are-the-log-presets-database-and-settings-stored).

**Comment by Aiphares** [comment]
oh god perfect, it works again! you are a hero thank you :D 

oh i did not know that it was known to cause a big problem since i just downloaded the program and had a go at it. i will make sure to never do it again and definitely try to get an eye for spotting empty references. 

Thank you again for the quick help!
